# Generated by Django 4.2.4 on 2023-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
