# Generated by Django 4.2.4 on 2023-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0002_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date',
            field=models.DateField(),
        ),
    ]
