# Generated by Django 4.2.4 on 2023-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Reg_No', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
